import type { AchievementDef, ConversationScenario, Domain, ExType, ModuleInfo, Phrase } from "./types";

/* ============================================================
   Curriculum content. The engine is content-agnostic: import
   more phrases (Settings → Content) and everything — sessions,
   SRS, modules, charts — keeps working at 500 / 1,000 / 5,000.
   Seed set: 60 phrases (30 everyday / 30 medical).
   ============================================================ */

export const MODULES: ModuleInfo[] = [
  { id: 1, title: "Greetings & Small Talk", domain: "everyday", blurb: "Open conversations naturally and keep them flowing." },
  { id: 2, title: "Opinions & Reactions", domain: "everyday", blurb: "React the way native speakers actually do." },
  { id: 3, title: "Plans, Favors & Requests", domain: "everyday", blurb: "Make plans and offer help without sounding stiff." },
  { id: 4, title: "Work & Problem Solving", domain: "everyday", blurb: "Handle tasks, uncertainty and clarification at work." },
  { id: 5, title: "Social Life & Phone Calls", domain: "everyday", blurb: "Calls, plans and easy-going social English." },
  { id: 6, title: "Patient Intake & Vital Signs", domain: "medical", blurb: "Check-in questions, history and vitals, politely." },
  { id: 7, title: "Blood Draws & Injections", domain: "medical", blurb: "Guide patients through procedures with calm language." },
  { id: 8, title: "Phones & Scheduling", domain: "medical", blurb: "Front-desk calls, appointments and confirmation." },
  { id: 9, title: "Lab Work & Results", domain: "medical", blurb: "Lab calls, fasting instructions and result language." },
  { id: 10, title: "Working With the Doctor", domain: "medical", blurb: "Clinical workflow communication with providers." },
];

export const EX_LABELS: Record<ExType, string> = {
  en_es: "Meaning",
  meaning: "Listening · meaning",
  context: "Choose the natural reply",
  fill: "Fill the blank",
  rebuild: "Rebuild the sentence",
  listen: "Listening · write meaning",
  dictation: "Dictation",
  es_en: "Translate to English",
  speaking: "Say it out loud",
  context_gen: "Respond in context",
  conversation: "Conversation",
};

interface Draft {
  pron?: string;
  mistakes?: string;
  exampleEs?: string;
}

function mk(
  id: string,
  module: number,
  domain: Domain,
  category: string,
  subcategory: string,
  difficulty: 1 | 2 | 3,
  en: string,
  es: string,
  alt: string,
  explain: string,
  grammar: string,
  scenario: string,
  example: string,
  concepts: string[][],
  tags: string[],
  d: Draft = {},
): Phrase {
  return { id, module, domain, category, subcategory, difficulty, en, es, alt, explain, grammar, scenario, example, concepts, tags, ...d };
}

export const PHRASES: Phrase[] = [
  /* ---------------- MODULE 1 · Greetings & Small Talk ---------------- */
  mk("p01", 1, "everyday", "Everyday English", "Greetings", 1,
    "How's it going?", "¿Cómo te va?", "¿Qué tal?",
    "The most common casual greeting in American English — friendlier and more relaxed than 'How are you?'",
    "Contraction of 'How is it going?'. Answer with a short positive: 'Good, you?'",
    "You see a coworker in the break room in the morning.",
    "Hey Marco — how's it going?",
    [["how's it going", "how is it going", "how are you", "how are you doing", "what's up", "how's everything"]],
    ["greeting", "casual"], { pron: "howz-it-GOH-in" }),
  mk("p02", 1, "everyday", "Everyday English", "Greetings", 1,
    "What have you been up to?", "¿Qué has estado haciendo?", "¿En qué has andado?",
    "Asks what someone has been doing since you last saw them. Perfect for catching up.",
    "Present perfect continuous idea: 'have been up to' = recent activities.",
    "You run into a friend you haven't seen in a few weeks.",
    "Ana! Long time — what have you been up to?",
    [["what have you been up to", "what have you been doing", "what's new", "what have you been up to lately"]],
    ["greeting", "catching up"]),
  mk("p03", 1, "everyday", "Everyday English", "Greetings", 1,
    "Long time no see!", "¡Cuánto tiempo sin verte!", "¡Tanto tiempo!",
    "A friendly, slightly playful way to greet someone you haven't seen in a while.",
    "Fixed expression — never changed to 'long times no see'.",
    "A former classmate walks into your workplace.",
    "No way — Luis! Long time no see!",
    [["long time no see", "it's been a while", "i haven't seen you in a long time", "it's been so long"]],
    ["greeting", "reunion"], { pron: "lahng-tym-noh-see" }),
  mk("p04", 1, "everyday", "Everyday English", "Small talk", 1,
    "I'm doing pretty well, thanks.", "Estoy bastante bien, gracias.", "Ando bastante bien, gracias.",
    "A natural, warm answer to 'How are you?' — 'pretty' softens it and sounds native.",
    "'Pretty' here means 'fairly / quite', not 'beautiful'.",
    "Your neighbor asks how you are by the mailbox.",
    "I'm doing pretty well, thanks. Busy week, though!",
    [["doing pretty well", "doing well", "doing good", "pretty good", "i'm good", "not bad"]],
    ["greeting", "response"]),
  mk("p05", 1, "everyday", "Everyday English", "Small talk", 1,
    "Can't complain.", "No me puedo quejar.", "Todo bien, sin quejas.",
    "A relaxed, positive reply that means life is fine. Very common in casual talk.",
    "Short for 'I can't complain.' Dropping the subject is natural in speech.",
    "A regular patient asks how your day is going.",
    "Can't complain! It's been a calm morning.",
    [["can't complain", "cannot complain", "no complaints", "everything's good", "all good"]],
    ["greeting", "response"], { pron: "kant-kum-PLAYN" }),
  mk("p06", 1, "everyday", "Everyday English", "Farewells", 1,
    "Have a good one!", "¡Que tengas un buen día!", "¡Que te vaya bien!",
    "The go-to casual farewell in the US — works any time of day, with anyone.",
    "'One' replaces 'day / afternoon / evening'. Never say 'have a good day one'.",
    "A customer is leaving the front desk.",
    "All set — have a good one!",
    [["have a good one", "have a good day", "take care", "see you later", "have a nice day"]],
    ["farewell", "casual"]),

  /* ---------------- MODULE 2 · Opinions & Reactions ---------------- */
  mk("p07", 2, "everyday", "Everyday English", "Reactions", 1,
    "That makes sense.", "Tiene sentido.", "Es lógico.",
    "Shows you understand and agree with someone's reasoning. Softens conversations.",
    "'Make sense' = be logical. Third person: 'That makes sense', not 'make'.",
    "A coworker explains why the schedule changed.",
    "Ah, that makes sense. Thanks for explaining.",
    [["makes sense", "that makes sense", "i see", "i understand", "that's logical", "i get it"]],
    ["agreement", "understanding"]),
  mk("p08", 2, "everyday", "Everyday English", "Decisions", 1,
    "It's up to you.", "Depende de ti.", "Tú decides.",
    "Politely passes a decision to the other person: you choose, I'm fine either way.",
    "'Up to + person' = decided by that person. Don't say 'it depends of you' here.",
    "Your friend can't decide which restaurant to go to.",
    "Either one is fine with me — it's up to you.",
    [["up to you", "it's up to you", "your call", "you decide", "it's your decision"]],
    ["decisions", "politeness"], { mistakes: "Saying 'it depends of you' — the phrase is 'up to you'." }),
  mk("p09", 2, "everyday", "Everyday English", "Apologies", 2,
    "I didn't mean to.", "No fue mi intención.", "No lo hice a propósito.",
    "A sincere, short apology when something accidental upset someone.",
    "'Mean to + verb' = intend. Past negative: 'didn't mean to (do it)'.",
    "You accidentally deleted a shared note a coworker needed.",
    "I'm so sorry — I didn't mean to delete it.",
    [["didn't mean to", "did not mean to", "didn't do it on purpose", "it was an accident", "wasn't my intention", "didn't mean it"]],
    ["apology", "intent"], { pron: "dih-DUNT-mee-nee-too" }),
  mk("p10", 2, "everyday", "Everyday English", "Reactions", 1,
    "You never know.", "Nunca se sabe.", "Vaya uno a saber.",
    "Says the future is uncertain — often optimistic: maybe something good will happen.",
    "Fixed phrase. Common after 'maybe…': 'Maybe she'll call — you never know.'",
    "A friend worries the job posting is already filled.",
    "Apply anyway — you never know.",
    [["you never know", "never know", "anything can happen", "it's possible"]],
    ["uncertainty", "optimism"]),
  mk("p11", 2, "everyday", "Everyday English", "Encouragement", 2,
    "It's worth a shot.", "Vale la pena intentarlo.", "No cuesta nada probar.",
    "Encourages trying something with low risk — even if success isn't certain.",
    "'A shot' = an attempt (informal). 'Worth + -ing / noun' pattern.",
    "Your sister hesitates about applying for a better-paying job.",
    "The commute is longer, but it's worth a shot.",
    [["worth a shot", "worth a try", "worth trying", "give it a shot", "give it a try", "nothing to lose"]],
    ["encouragement", "idiom"], { pron: "werts-uh-SHOT" }),
  mk("p12", 2, "everyday", "Everyday English", "Discussion", 2,
    "I see your point.", "Entiendo tu punto.", "Veo tu punto de vista.",
    "Acknowledges someone's argument before (often) disagreeing gently.",
    "'Point' = argument/idea. Often followed by 'but…' to soften disagreement.",
    "A teammate proposes an idea you only half agree with.",
    "I see your point, but the budget won't allow it this month.",
    [["see your point", "i get your point", "i understand your point", "i see what you mean", "you have a point", "i see where you're coming from"]],
    ["discussion", "disagreement"]),

  /* ---------------- MODULE 3 · Plans, Favors & Requests ---------------- */
  mk("p13", 3, "everyday", "Everyday English", "Offers", 1,
    "I'll take care of it.", "Yo me encargo.", "Déjamelo a mí.",
    "A confident promise to handle a task. The #1 way Americans volunteer for work.",
    "'Take care of + thing' = handle/resolve. 'I'll' = I will (instant decision).",
    "Your coworker asks if someone can restock the supply closet.",
    "Don't worry about it — I'll take care of it.",
    [["take care of it", "i'll handle it", "i'll deal with it", "i got it", "i've got it", "i'll do it", "on it"]],
    ["offers", "work"], { mistakes: "'I take care it' — you need the future 'I'll' and the preposition 'of'." }),
  mk("p14", 3, "everyday", "Everyday English", "Decisions", 1,
    "Let me think about it.", "Déjame pensarlo.", "Necesito pensarlo.",
    "Buys time before deciding — polite, and very common for invitations and offers.",
    "'Let me + verb' = allow me to. Object pronoun attaches: 'think about IT'.",
    "A friend invites you to a trip next month, but you're unsure about money.",
    "Sounds fun! Let me think about it and get back to you.",
    [["think about it", "let me think", "i need to think", "let me think about it", "i'll think it over"]],
    ["decisions", "politeness"]),
  mk("p15", 3, "everyday", "Everyday English", "Plans", 1,
    "Are you free this weekend?", "¿Estás libre este fin de semana?", "¿Tienes planes este fin de semana?",
    "The standard way to open an invitation or plan for Saturday/Sunday.",
    "'Free' = available. 'This weekend' needs no preposition (not 'in this weekend').",
    "You want to invite a friend to a barbecue on Saturday.",
    "Are you free this weekend? We're having a cookout.",
    [["are you free", "you free", "are you available", "do you have plans", "are you busy", "you got plans"]],
    ["plans", "invitations"], { mistakes: "'Are you free in this weekend?' — no preposition before 'this weekend'." }),
  mk("p16", 3, "everyday", "Everyday English", "Requests", 1,
    "Could you do me a favor?", "¿Podrías hacerme un favor?", "¿Me harías un favor?",
    "A polite set-up before asking for help. Softens any request that follows.",
    "'Do someone a favor' — indirect object before 'a favor'. 'Could' = more polite than 'can'.",
    "You need a coworker to cover the front desk for ten minutes.",
    "Hey, could you do me a favor and watch the desk real quick?",
    [["do me a favor", "could you help me", "can you do me a favor", "could you help me out", "give me a hand"]],
    ["requests", "politeness"]),
  mk("p17", 3, "everyday", "Everyday English", "Plans", 2,
    "Let's play it by ear.", "Decidamos sobre la marcha.", "Veamos cómo se da.",
    "Suggests staying flexible instead of making a fixed plan.",
    "Idiom from music: playing without sheet music. 'By ear', never 'by the ear'.",
    "The weather forecast is uncertain for Saturday's picnic.",
    "Let's play it by ear — if it rains, we'll just do dinner instead.",
    [["play it by ear", "let's see how it goes", "we'll improvise", "let's be flexible", "we'll figure it out later", "let's wait and see"]],
    ["plans", "idiom"], { pron: "play-it-by-EER" }),
  mk("p18", 3, "everyday", "Everyday English", "Time", 1,
    "I'm running a bit late.", "Voy un poco tarde.", "Se me está haciendo tarde.",
    "The natural way to say you'll arrive a few minutes behind schedule.",
    "'Run late' = be behind schedule. 'A bit' softens it; 'running VERY late' = serious.",
    "Traffic is bad and your 9:00 meeting starts in five minutes.",
    "Hey — I'm running a bit late. I'll be there by 9:10.",
    [["running late", "running a bit late", "running a little late", "i'll be a little late", "i'm going to be late"]],
    ["time", "calls"]),

  /* ---------------- MODULE 4 · Work & Problem Solving ---------------- */
  mk("p19", 4, "everyday", "Everyday English", "Problem solving", 1,
    "I'll figure it out.", "Ya lo resolveré.", "Yo lo averiguo.",
    "Shows confidence in solving a problem without help. Very common at US workplaces.",
    "'Figure out' = solve/understand. Separable: 'figure IT out', not 'figure out it'.",
    "The printer is jammed and nobody knows why.",
    "It's okay, I'll figure it out — it happened last week too.",
    [["figure it out", "i'll find out", "i'll solve it", "i'll work it out", "i'll sort it out", "i'll handle it"]],
    ["problem solving", "confidence"], { mistakes: "'I'll figure out it' — the pronoun must go inside: figure it out." }),
  mk("p20", 4, "everyday", "Everyday English", "Uncertainty", 1,
    "It depends on the schedule.", "Depende del horario.", "Según el horario.",
    "Says an answer changes based on one condition — the polite way to say 'maybe'.",
    "'Depend ON' — always with 'on', never 'depend of'.",
    "A client asks if you can start their project next week.",
    "It depends on the schedule — let me check with the team.",
    [["depends on", "it depends on", "depends", "it depends", "depending on"]],
    ["uncertainty", "work"], { mistakes: "'It depends of the schedule' — in English it's 'depend ON'." }),
  mk("p21", 4, "everyday", "Everyday English", "Uncertainty", 2,
    "As far as I know, we're on track.", "Que yo sepa, vamos bien.", "Hasta donde sé, vamos según lo planeado.",
    "Gives information while honestly limiting your responsibility for it.",
    "'As far as I know' + statement. 'On track' = progressing as planned.",
    "Your manager asks about the status of the monthly report.",
    "As far as I know, we're on track for Friday.",
    [["as far as i know", "to my knowledge", "that i know of", "i think we're on track", "from what i know"]],
    ["uncertainty", "status"], { pron: "az-far-az-eye-NOH" }),
  mk("p22", 4, "everyday", "Everyday English", "Reactions", 1,
    "I didn't realize that.", "No me había dado cuenta.", "No lo sabía.",
    "Admits you were unaware of something — polite and honest, never defensive.",
    "'Realize' = become aware (not 'make real'). Past: 'didn't realize'.",
    "A coworker tells you the meeting room changed an hour ago.",
    "Oh, I didn't realize that — thanks for telling me.",
    [["didn't realize", "did not realize", "i had no idea", "i didn't know that", "i wasn't aware"]],
    ["reactions", "honesty"]),
  mk("p23", 4, "everyday", "Everyday English", "Clarification", 2,
    "Let me make sure I understand correctly.", "Déjame asegurarme de que entiendo bien.", "Permíteme confirmar que entendí bien.",
    "A professional way to paraphrase and verify instructions — prevents mistakes.",
    "'Make sure' + clause. Follow it with your summary: 'So you need X by Y?'",
    "Your supervisor gives you a multi-step task quickly.",
    "Let me make sure I understand correctly — you want the forms scanned AND emailed?",
    [["make sure i understand", "let me confirm", "just to clarify", "so what you're saying is", "let me make sure", "i want to make sure i understand"]],
    ["clarification", "work"]),
  mk("p24", 4, "everyday", "Everyday English", "Preferences", 1,
    "It doesn't matter to me.", "A mí no me importa.", "Me da igual.",
    "Says you have no strong preference — neutral and easy-going, not rude.",
    "'Matter to + person' = be important to. Tone decides if it sounds relaxed or cold.",
    "Two friends debate whether to meet at 6 or 7.",
    "Either time works — it doesn't matter to me.",
    [["doesn't matter", "does not matter to me", "it doesn't matter", "either works", "i don't mind", "i'm fine with either"]],
    ["preferences", "neutral"]),

  /* ---------------- MODULE 5 · Social Life & Phone Calls ---------------- */
  mk("p25", 5, "everyday", "Everyday English", "Phone", 1,
    "I was about to call you.", "Estaba a punto de llamarte.", "Justo te iba a llamar.",
    "A friendly coincidence line when someone calls at the perfect moment.",
    "'Was/were about to + verb' = on the point of doing something.",
    "Your mom calls the exact second you pick up your phone to dial her.",
    "Funny — I was about to call you!",
    [["was about to call", "i was just going to call", "i was just about to call", "i was going to call you", "about to call you"]],
    ["phone", "coincidence"], { pron: "uh-BOW-too" }),
  mk("p26", 5, "everyday", "Everyday English", "Clarification", 1,
    "What do you mean?", "¿Qué quieres decir?", "¿A qué te refieres?",
    "Asks someone to explain or clarify. Neutral — tone makes it curious, not aggressive.",
    "Present simple question form. Softer variant: 'What do you mean by that?'",
    "A friend texts 'we need to talk' with no details.",
    "What do you mean? Is everything okay?",
    [["what do you mean", "what does that mean", "what are you talking about", "i don't understand", "what do you mean by that"]],
    ["clarification", "questions"]),
  mk("p27", 5, "everyday", "Everyday English", "Phone", 1,
    "Can I call you back?", "¿Puedo devolverte la llamada?", "¿Te marco más tarde?",
    "Politely ends a call you can't take right now, promising to return it.",
    "'Call back' = return a call. Separable: 'call YOU back'.",
    "Your phone rings while you're checking a patient into the exam room.",
    "Sorry, I'm with someone — can I call you back in ten minutes?",
    [["call you back", "call back", "i'll call you back", "let me call you back", "i'll get back to you"]],
    ["phone", "politeness"]),
  mk("p28", 5, "everyday", "Everyday English", "Agreement", 1,
    "Sounds good to me.", "Me parece bien.", "Suena bien.",
    "An easy, upbeat way to agree to plans or suggestions.",
    "'Sounds' = 'That sounds'. Dropping the subject is natural: 'Sounds good!'",
    "A friend suggests tacos and a movie on Friday.",
    "Sounds good to me — should I drive?",
    [["sounds good", "sounds good to me", "that sounds good", "works for me", "sounds great", "i'm in"]],
    ["agreement", "plans"]),
  mk("p29", 5, "everyday", "Everyday English", "Promises", 1,
    "I'll let you know.", "Te aviso.", "Te hago saber.",
    "Promises to share information later, once you have it. Used constantly at work.",
    "'Let someone know' = inform. Future 'I'll' shows you're committing now.",
    "A friend asks if you got the concert tickets.",
    "They go on sale at noon — I'll let you know.",
    [["let you know", "i'll let you know", "i'll tell you", "i'll keep you posted", "i'll get back to you", "i'll keep you updated"]],
    ["promises", "work"]),
  mk("p30", 5, "everyday", "Everyday English", "Reassurance", 1,
    "No worries at all.", "No te preocupes para nada.", "Cero preocupación.",
    "Warmly dismisses an apology or thanks — says the problem was truly nothing.",
    "'No worries' = it's fine. 'At all' adds emphasis and warmth.",
    "A patient apologizes for arriving five minutes late.",
    "No worries at all — we're right on schedule.",
    [["no worries", "no worries at all", "don't worry about it", "it's no problem", "no problem at all", "it's all good"]],
    ["reassurance", "politeness"]),

  /* ---------------- MODULE 6 · Patient Intake & Vital Signs ---------------- */
  mk("p31", 6, "medical", "Medical English", "Vital signs", 1,
    "Let me check your blood pressure.", "Déjeme tomarle la presión arterial.", "Voy a revisarle la presión.",
    "Standard MA phrasing before measuring BP — calm, clear, and professional.",
    "'Let me + verb' is a soft professional command. 'Check' sounds gentler than 'measure'.",
    "You're rooming a patient for a routine visit.",
    "Let me check your blood pressure — could you rest your arm on the table?",
    [["check your blood pressure", "take your blood pressure", "check your bp", "measure your blood pressure", "let me check your blood pressure"]],
    ["vitals", "procedure"]),
  mk("p32", 6, "medical", "Medical English", "Vital signs", 1,
    "I'm going to take your temperature.", "Voy a tomarle la temperatura.", "Le voy a medir la fiebre.",
    "Announces the next step before touching the thermometer — builds trust.",
    "'Going to' for planned actions. 'Take a temperature' is the fixed collocation.",
    "A patient comes in with flu-like symptoms.",
    "I'm going to take your temperature — just hold this under your tongue.",
    [["take your temperature", "check your temperature", "measure your temperature", "going to take your temperature"]],
    ["vitals", "procedure"]),
  mk("p33", 6, "medical", "Medical English", "Intake questions", 1,
    "Are you taking any medications?", "¿Está tomando algún medicamento?", "¿Toma alguna medicina?",
    "The standard medication-history question at every intake.",
    "Present continuous for current, ongoing use. 'Any' in questions.",
    "You're updating the chart for a new patient.",
    "Are you taking any medications right now, including vitamins?",
    [["taking any medications", "on any medications", "taking any medication", "do you take any medications", "are you on any meds", "taking any meds"]],
    ["intake", "medications"]),
  mk("p34", 6, "medical", "Medical English", "Intake questions", 1,
    "Do you have any allergies?", "¿Tiene alguna alergia?", "¿Es alérgico a algo?",
    "The safety-critical allergy question — asked at every single visit.",
    "Simple present for permanent states. Always pair with: 'to any medications?'",
    "A new patient is filling out intake forms at your desk.",
    "Do you have any allergies — medications, food, or latex?",
    [["have any allergies", "any allergies", "allergic to anything", "do you have allergies", "are you allergic to anything"]],
    ["intake", "safety"]),
  mk("p35", 6, "medical", "Medical English", "History", 2,
    "When did your symptoms start?", "¿Cuándo comenzaron sus síntomas?", "¿Desde cuándo tiene los síntomas?",
    "Opens the history of present illness — the first question doctors need answered.",
    "Past simple question: 'When did + subject + base verb'.",
    "A patient tells you they've been feeling unwell.",
    "When did your symptoms start — suddenly or gradually?",
    [["when did your symptoms start", "when did the symptoms start", "when did it start", "how long have you had the symptoms", "when did you start feeling"]],
    ["history", "questions"]),
  mk("p36", 6, "medical", "Medical English", "History", 2,
    "Have your symptoms gotten worse?", "¿Han empeorado sus síntomas?", "¿Se han puesto peor los síntomas?",
    "Checks progression — key for deciding urgency and triage.",
    "Present perfect: 'have + gotten + comparative'. 'Gotten worse' = American for 'become worse'.",
    "A patient was here last week with a cough that won't quit.",
    "Since your last visit — have your symptoms gotten worse?",
    [["gotten worse", "got worse", "have your symptoms gotten worse", "symptoms getting worse", "is it getting worse", "are they getting worse"]],
    ["history", "triage"], { mistakes: "'Have your symptoms become worst?' — use the comparative: gotten WORSE." }),

  /* ---------------- MODULE 7 · Blood Draws & Injections ---------------- */
  mk("p37", 7, "medical", "Medical English", "Blood draws", 1,
    "I'm going to draw some blood.", "Voy a extraerle sangre.", "Le voy a sacar sangre.",
    "The standard, calm way to announce a venipuncture. 'Draw' is the professional term.",
    "'Draw blood' is the fixed collocation — not 'pull' or 'extract' in speech.",
    "A patient sits down in the lab chair for a CBC.",
    "I'm going to draw some blood — it'll just take a minute.",
    [["draw some blood", "draw blood", "take some blood", "going to draw some blood", "do a blood draw"]],
    ["blood draw", "procedure"]),
  mk("p38", 7, "medical", "Medical English", "Blood draws", 1,
    "You may feel a little pressure.", "Puede que sienta una pequeña presión.", "Quizás sienta un poco de presión.",
    "Prepares the patient for the sensation without saying scary words like 'pain'.",
    "'May + verb' = gentle possibility. 'A little' keeps it reassuring.",
    "You're about to insert the needle for a blood draw.",
    "You may feel a little pressure — almost done.",
    [["feel a little pressure", "feel some pressure", "you may feel a pinch", "a little pinch", "feel a little pressure", "small pinch"]],
    ["blood draw", "reassurance"]),
  mk("p39", 7, "medical", "Medical English", "Instructions", 1,
    "Please roll up your sleeve.", "Por favor, súbase la manga.", "Arremánguese, por favor.",
    "The universal pre-blood-draw instruction — short, clear, polite with 'please'.",
    "Phrasal verb 'roll up' + object. Imperative + 'please' = polite command.",
    "The patient sits down and you prepare the tourniquet.",
    "Please roll up your sleeve — the left arm works best.",
    [["roll up your sleeve", "roll up your sleeves", "push up your sleeve", "roll your sleeve up", "sleeve up"]],
    ["instructions", "blood draw"]),
  mk("p40", 7, "medical", "Medical English", "Blood draws", 1,
    "Make a fist for me, please.", "Haga un puño, por favor.", "Cierre el puño, por favor.",
    "Helps veins become visible before the draw. 'For me' adds warmth to the command.",
    "Imperative + 'for me, please' — friendly professional request pattern.",
    "You tie the tourniquet and look for a good vein.",
    "Make a fist for me, please… perfect, I see a good one.",
    [["make a fist", "clench your fist", "squeeze your fist", "make a fist for me", "clench your hand"]],
    ["blood draw", "instructions"]),
  mk("p41", 7, "medical", "Medical English", "Monitoring", 2,
    "Are you feeling any dizziness?", "¿Siente algún mareo?", "¿Se siente mareado?",
    "Screens for a common reaction during or after blood draws and injections.",
    "'Any' + uncountable noun in questions. 'Feeling dizzy' is the patient's word; 'dizziness' is clinical.",
    "A patient looks pale during the draw.",
    "Are you feeling any dizziness or lightheadedness right now?",
    [["feeling any dizziness", "feeling dizzy", "any dizziness", "do you feel dizzy", "are you dizzy", "feeling lightheaded"]],
    ["monitoring", "safety"]),
  mk("p42", 7, "medical", "Medical English", "Instructions", 1,
    "Hold still for just a second.", "Quédese quieto un segundo.", "No se mueva un momento.",
    "A calm, time-limited instruction — 'just a second' makes it feel easy.",
    "'Hold still' = don't move. 'Just a second' minimizes the request.",
    "You're giving an IM injection and the patient tenses up.",
    "Hold still for just a second — and done. Great job.",
    [["hold still", "stay still", "don't move", "hold still for a second", "keep still"]],
    ["injections", "instructions"]),

  /* ---------------- MODULE 8 · Phones & Scheduling ---------------- */
  mk("p43", 8, "medical", "Medical English", "Front desk", 1,
    "The doctor will be with you shortly.", "El doctor la atenderá en breve.", "El doctor estará con usted en un momento.",
    "The classic waiting-room reassurance. 'Shortly' sounds professional and warm.",
    "'Be with you' = attend to you. 'Shortly' ≈ soon, but more professional.",
    "A checked-in patient asks how long the wait will be.",
    "You're all set — the doctor will be with you shortly.",
    [["will be with you shortly", "will be with you soon", "the doctor will see you soon", "will be with you in a moment", "be with you shortly"]],
    ["front desk", "reassurance"]),
  mk("p44", 8, "medical", "Medical English", "Verification", 1,
    "Let me confirm your date of birth.", "Déjeme confirmar su fecha de nacimiento.", "Permítame verificar su fecha de nacimiento.",
    "Patient-identity verification — required before any record is opened.",
    "'Confirm' + noun. 'Date of birth' = DOB. Ask for the full date, not the year alone.",
    "You call a patient's chart up on the computer.",
    "Let me confirm your date of birth — is it March 4th, 1988?",
    [["confirm your date of birth", "verify your date of birth", "what's your date of birth", "can i get your date of birth", "confirm your dob"]],
    ["verification", "front desk"]),
  mk("p45", 8, "medical", "Medical English", "Scheduling", 2,
    "Would you like to reschedule your appointment?", "¿Desea reprogramar su cita?", "¿Quiere cambiar su cita?",
    "Offers a new time when a patient needs to cancel — keeps the visit on the books.",
    "'Would you like to + verb' = polite offer. 'Reschedule' is the formal front-desk verb.",
    "A patient calls saying they can't make Friday's appointment.",
    "No problem — would you like to reschedule your appointment for next week?",
    [["reschedule your appointment", "reschedule", "would you like to reschedule", "move your appointment", "pick another time", "find another time"]],
    ["scheduling", "phone"]),
  mk("p46", 8, "medical", "Medical English", "Scheduling", 1,
    "We have an opening at 2:30.", "Tenemos un espacio a las 2:30.", "Hay una cita disponible a las 2:30.",
    "Offers a specific available slot. 'Opening' sounds natural; 'free space' doesn't.",
    "'An opening' = an available appointment slot. Time with 'at'.",
    "A patient needs the soonest possible visit today.",
    "Let me check… yes, we have an opening at 2:30 today.",
    [["have an opening", "there's an opening", "opening at", "we have an opening", "slot at", "we have something at"]],
    ["scheduling", "front desk"], { mistakes: "'We have a free space at 2:30' — for appointments, say 'an opening' or 'a slot'." }),
  mk("p47", 8, "medical", "Medical English", "Phone", 2,
    "I'll put you on a brief hold.", "La pondré en espera un momento.", "Espere un momentito en la línea.",
    "Professional hold language — 'brief' reassures the caller it won't be long.",
    "'Put someone on hold' is the fixed phone phrase. 'Brief' = short.",
    "You need to ask the nurse about a refill while a patient waits on the line.",
    "I'll put you on a brief hold while I check with the nurse.",
    [["put you on hold", "put you on a brief hold", "hold for a moment", "can you hold", "i'll place you on hold"]],
    ["phone", "front desk"]),
  mk("p48", 8, "medical", "Medical English", "Verification", 1,
    "Could you spell your last name for me?", "¿Puede deletrear su apellido?", "¿Me deletrea su apellido?",
    "Gets exact spelling for records and searches. 'For me' softens the request.",
    "'Spell' + object. 'Last name' = surname/family name (US English).",
    "The patient's name isn't coming up in the system.",
    "Could you spell your last name for me? … G-A-R-C-I-A, got it.",
    [["spell your last name", "spell your last name for me", "can you spell that", "how do you spell your last name", "spell your surname"]],
    ["verification", "phone"]),

  /* ---------------- MODULE 9 · Lab Work & Results ---------------- */
  mk("p49", 9, "medical", "Medical English", "Lab communication", 2,
    "The lab hasn't released the final results yet.", "El laboratorio aún no ha entregado los resultados finales.", "El laboratorio todavía no libera los resultados finales.",
    "Explains a results delay accurately without blaming anyone or guessing.",
    "Present perfect negative + 'yet'. 'Release results' is standard lab language.",
    "A patient calls, anxious about labs drawn three days ago.",
    "The lab hasn't released the final results yet — we expect them tomorrow.",
    [["hasn't released", "has not released the results", "results aren't back yet", "the results aren't ready yet", "hasn't released the final results", "lab hasn't released"]],
    ["lab", "results"]),
  mk("p50", 9, "medical", "Medical English", "Lab communication", 2,
    "I'm calling regarding a patient's lab results.", "Llamo respecto a los resultados de laboratorio de un paciente.", "Le llamo por los resultados de un paciente.",
    "The professional opener for provider-to-lab or clinic-to-provider calls.",
    "'Regarding' = about (formal). Possessive: 'a patient's lab results'.",
    "You call the reference lab to follow up on a missing panel.",
    "Hi, this is Rosa from Family Care — I'm calling regarding a patient's lab results.",
    [["calling regarding", "calling about", "i'm calling regarding", "calling in regards to", "calling about a patient's lab results"]],
    ["lab", "phone"], { pron: "reh-GAR-ding" }),
  mk("p51", 9, "medical", "Medical English", "Results", 1,
    "Your results came back normal.", "Sus resultados salieron normales.", "Sus resultados están normales.",
    "Delivers good lab news. 'Came back' is how results 'arrive' in English.",
    "'Come back + adjective' = return with a value. Never 'the results are normal came'.",
    "The doctor asked you to relay the routine panel results.",
    "Good news — your results came back normal.",
    [["came back normal", "results came back normal", "results are normal", "everything came back normal", "your results are normal"]],
    ["lab", "results"]),
  mk("p52", 9, "medical", "Medical English", "Lab instructions", 2,
    "You'll need to fast for twelve hours.", "Deberá ayunar durante doce horas.", "Tiene que venir en ayunas de doce horas.",
    "Clear fasting instruction before glucose or lipid panels.",
    "'Need to + verb' = requirement. 'Fasting' = no food or drink except water.",
    "You're scheduling a fasting glucose test for tomorrow morning.",
    "You'll need to fast for twelve hours — water is fine.",
    [["fast for", "fasting for", "you'll need to fast", "need to fast", "don't eat for", "no food for"]],
    ["lab", "instructions"]),
  mk("p53", 9, "medical", "Medical English", "Results", 2,
    "The doctor will discuss the results with you.", "El doctor hablará con usted sobre los resultados.", "El médico le explicará los resultados.",
    "Sets the right expectation: results are explained by the provider, not the front desk.",
    "'Discuss + object + with + person' — 'discuss about' is incorrect.",
    "A patient asks you to interpret an abnormal value on the phone.",
    "I can see the value, but the doctor will discuss the results with you at your visit.",
    [["discuss the results", "the doctor will discuss", "go over the results", "review the results with you", "talk about the results", "explain the results"]],
    ["results", "boundaries"], { mistakes: "'The doctor will discuss about the results' — 'discuss' never takes 'about'." }),
  mk("p54", 9, "medical", "Medical English", "Verification", 1,
    "Could you confirm the patient's date of birth?", "¿Puede confirmar la fecha de nacimiento del paciente?", "¿Me confirma la fecha de nacimiento del paciente?",
    "Identity check when calling other clinics or labs — protects patient privacy (HIPAA).",
    "'Could you + verb' = polite request. Third-person: 'the patient's', not 'your'.",
    "A lab rep asks you to verify who you're calling about.",
    "Could you confirm the patient's date of birth and last name?",
    [["confirm the patient's date of birth", "verify the patient's date of birth", "confirm the dob", "patient's date of birth", "can you confirm the date of birth"]],
    ["verification", "lab"]),

  /* ---------------- MODULE 10 · Working With the Doctor ---------------- */
  mk("p55", 10, "medical", "Medical English", "Workflow", 1,
    "Would you like me to bring the next patient in?", "¿Quiere que haga pasar al siguiente paciente?", "¿Le traigo al siguiente paciente?",
    "The classic MA-to-provider workflow offer — proactive and professional.",
    "'Would you like me to + verb' = offer to act. Very high-frequency in clinics.",
    "The doctor finishes charting and the waiting room is full.",
    "Would you like me to bring the next patient in?",
    [["bring the next patient in", "would you like me to bring", "bring in the next patient", "should i bring the next patient", "send the next patient in", "get the next patient"]],
    ["workflow", "offers"], { mistakes: "'Would you like me bring the next patient?' — you need 'to': would you like me TO bring…." }),
  mk("p56", 10, "medical", "Medical English", "Workflow", 1,
    "I'll let the doctor know.", "Le avisaré al doctor.", "Le comento al doctor.",
    "Closes the loop when a patient shares information meant for the provider.",
    "'Let someone know' = inform. 'I'll' commits you to the action right now.",
    "A patient mentions a new medication their doctor hasn't seen yet.",
    "Thanks for telling me — I'll let the doctor know.",
    [["let the doctor know", "i'll let the doctor know", "tell the doctor", "i'll inform the doctor", "i'll pass that on to the doctor", "i'll tell the doctor"]],
    ["workflow", "communication"]),
  mk("p57", 10, "medical", "Medical English", "Workflow", 1,
    "Room two is ready for you.", "La sala dos está lista para usted.", "El consultorio dos lo espera.",
    "Directs the provider (or patient) efficiently. Short, clear, polite.",
    "'Ready for + person'. Room numbers without 'the': 'Room two', not 'the room two'.",
    "You finish setting up the exam room and flag down the doctor.",
    "Room two is ready for you — it's the annual physical.",
    [["room two is ready", "is ready for you", "the room is ready", "room two's ready", "exam room is ready"]],
    ["workflow", "rooms"]),
  mk("p58", 10, "medical", "Medical English", "Courtesy", 1,
    "Would you like me to close the door?", "¿Quiere que cierre la puerta?", "¿Le cierro la puerta?",
    "A small courtesy that protects privacy during exams and sensitive talks.",
    "'Would you like me to + verb' — the same offer pattern as #55.",
    "You're about to leave the exam room during a sensitive visit.",
    "Would you like me to close the door on my way out?",
    [["close the door", "would you like me to close", "should i close the door", "want me to close the door", "shall i close the door"]],
    ["courtesy", "privacy"]),
  mk("p59", 10, "medical", "Medical English", "Workflow", 1,
    "I'll bring them in right away.", "Lo hago pasar de inmediato.", "Enseguida lo paso.",
    "A crisp, immediate acceptance when the doctor asks you to room a patient.",
    "'Right away' = immediately. 'Them' is the natural singular-them for a patient.",
    "The doctor texts: 'Can you send Mrs. Chen in?'",
    "I'll bring them in right away.",
    [["bring them in", "i'll bring them in", "right away", "send them in", "i'll get them right away", "bring them in right away"]],
    ["workflow", "responses"]),
  mk("p60", 10, "medical", "Medical English", "Workflow", 2,
    "Let me grab the chart for you.", "Déjeme buscarle el expediente.", "Le consigo la historia clínica.",
    "Offers to fetch the record — 'grab' is friendly workplace English for 'get quickly'.",
    "'Grab' = get quickly (informal but standard at work). 'Chart' = medical record.",
    "The doctor needs the file for the patient waiting in room three.",
    "Let me grab the chart for you — it's right at the desk.",
    [["grab the chart", "get the chart", "pull the chart", "let me grab the chart", "i'll pull up the chart", "get the chart for you"]],
    ["workflow", "records"]),
];

/* ---------------- Conversation scenarios ---------------- */

export const CONVERSATIONS: ConversationScenario[] = [
  {
    id: "cv-checkin",
    title: "Front-Desk Check-In",
    domain: "medical",
    difficulty: 1,
    role: "Medical assistant at the front desk",
    partner: "Patient",
    setting: "A patient arrives for a 10:30 appointment.",
    turns: [
      { speaker: "partner", text: "Hi, I have an appointment at 10:30.", model: "", concepts: [] },
      {
        speaker: "user",
        context: "Greet the patient and ask for their name.",
        model: "Sure — could I get your name, please?",
        concepts: [["name", "your name", "can i get your name", "could i have your name", "what's your name"]],
        tip: "Front-desk standard: 'Could I get your name, please?'",
      },
      { speaker: "partner", text: "It's Marta Ruiz.", model: "", concepts: [] },
      {
        speaker: "user",
        context: "Verify her identity — ask for her date of birth.",
        model: "Thanks, Marta. Let me confirm your date of birth.",
        concepts: [["date of birth", "dob", "when were you born", "birthday", "your birth date"]],
      },
      { speaker: "partner", text: "June 12th, 1990.", model: "", concepts: [] },
      {
        speaker: "user",
        context: "Confirm the appointment and tell her the doctor will see her soon.",
        model: "Perfect — you're all set. The doctor will be with you shortly.",
        concepts: [["all set", "you're set", "confirmed", "doctor will be with you", "will see you soon", "shortly"]],
        tip: "'You're all set' + 'the doctor will be with you shortly' is the classic combo.",
      },
    ],
  },
  {
    id: "cv-vitals",
    title: "Taking Vital Signs",
    domain: "medical",
    difficulty: 1,
    role: "Medical assistant rooming a patient",
    partner: "Patient",
    setting: "You're taking vitals before the doctor comes in.",
    turns: [
      { speaker: "partner", text: "Hi — the front desk said you'd take my vitals?", model: "", concepts: [] },
      {
        speaker: "user",
        context: "Confirm, and tell them you'll check their blood pressure.",
        model: "That's right. Let me check your blood pressure first.",
        concepts: [["blood pressure", "check your blood pressure", "take your blood pressure", "bp"]],
      },
      { speaker: "partner", text: "Okay. Do I need to do anything?", model: "", concepts: [] },
      {
        speaker: "user",
        context: "Ask them to relax their arm and rest it on the table.",
        model: "Just relax your arm and rest it on the table, please.",
        concepts: [["arm", "relax", "rest", "table", "your arm on the table"]],
      },
      { speaker: "partner", text: "Sure… is it high?", model: "", concepts: [] },
      {
        speaker: "user",
        context: "Say it looks fine, and tell them the doctor will review everything.",
        model: "It looks fine. The doctor will go over everything with you.",
        concepts: [["fine", "looks good", "normal", "doctor will", "review", "go over", "discuss"]],
      },
    ],
  },
  {
    id: "cv-labcall",
    title: "Calling the Lab",
    domain: "medical",
    difficulty: 2,
    role: "Medical assistant calling a reference lab",
    partner: "Lab receptionist",
    setting: "A patient's lab results are missing from the portal.",
    turns: [
      { speaker: "partner", text: "Quest Diagnostics, how can I help you?", model: "", concepts: [] },
      {
        speaker: "user",
        context: "Say who you are and that you're calling about a patient's lab results.",
        model: "Hi, this is Rosa from Family Care Clinic. I'm calling regarding a patient's lab results.",
        concepts: [["calling regarding", "calling about", "lab results", "patient's lab results", "results"]],
        tip: "'I'm calling regarding…' is the professional opener.",
      },
      { speaker: "partner", text: "Of course. Can I get the patient's full name?", model: "", concepts: [] },
      {
        speaker: "user",
        context: "Give the name and offer to confirm the date of birth.",
        model: "It's Marta Ruiz, born June 12th, 1990 — I can confirm her date of birth if you need it.",
        concepts: [["confirm", "date of birth", "born", "dob"]],
      },
      { speaker: "partner", text: "That's fine. What was drawn and when?", model: "", concepts: [] },
      {
        speaker: "user",
        context: "Say it was a CBC drawn on Monday, and ask when the results will be ready.",
        model: "A CBC drawn on Monday morning. Do you know when the results will be released?",
        concepts: [["cbc", "monday", "when", "results", "released", "ready"]],
      },
    ],
  },
  {
    id: "cv-reschedule",
    title: "Rescheduling by Phone",
    domain: "medical",
    difficulty: 2,
    role: "Front-desk medical assistant",
    partner: "Patient on the phone",
    setting: "A patient needs to move Friday's appointment.",
    turns: [
      { speaker: "partner", text: "Hi, something came up — I can't make it on Friday.", model: "", concepts: [] },
      {
        speaker: "user",
        context: "Be understanding and offer to reschedule.",
        model: "No problem at all. Would you like to reschedule your appointment?",
        concepts: [["reschedule", "no problem", "another time", "move", "find another time", "pick another day"]],
      },
      { speaker: "partner", text: "Yes, please. What do you have next week?", model: "", concepts: [] },
      {
        speaker: "user",
        context: "Offer a specific opening.",
        model: "Let me check… we have an opening Tuesday at 2:30. Does that work?",
        concepts: [["opening", "slot", "tuesday", "2:30", "does that work", "available"]],
        tip: "For appointments, say 'an opening' or 'a slot' — not 'a free space'.",
      },
      { speaker: "partner", text: "Tuesday works. Thank you!", model: "", concepts: [] },
      {
        speaker: "user",
        context: "Confirm the new time and close the call warmly.",
        model: "Great — you're all set for Tuesday at 2:30. Have a good one!",
        concepts: [["all set", "confirmed", "tuesday", "see you", "have a good", "you're set"]],
      },
    ],
  },
  {
    id: "cv-smalltalk",
    title: "Coffee Break with a Coworker",
    domain: "everyday",
    difficulty: 1,
    role: "You",
    partner: "Coworker",
    setting: "You bump into a coworker in the break room.",
    turns: [
      { speaker: "partner", text: "Hey! I feel like I haven't seen you in forever.", model: "", concepts: [] },
      {
        speaker: "user",
        context: "Agree — it's been a while — and ask what they've been up to.",
        model: "I know, long time no see! What have you been up to?",
        concepts: [["long time", "been a while", "what have you been up to", "what's new", "been up to"]],
      },
      { speaker: "partner", text: "Mostly just the new project. It's a lot, honestly.", model: "", concepts: [] },
      {
        speaker: "user",
        context: "Show empathy and offer help.",
        model: "I can imagine. Let me know if I can help with anything.",
        concepts: [["imagine", "sounds like a lot", "help", "let me know", "i can help", "that sounds rough"]],
      },
      { speaker: "partner", text: "Thanks, that means a lot. Want to grab coffee Friday?", model: "", concepts: [] },
      {
        speaker: "user",
        context: "Accept warmly and suggest a time or say you'll confirm later.",
        model: "Sounds good to me! I'll let you know by Thursday.",
        concepts: [["sounds good", "sure", "let you know", "i'm in", "sounds great", "works for me"]],
      },
    ],
  },
  {
    id: "cv-restaurant",
    title: "Ordering at a Restaurant",
    domain: "everyday",
    difficulty: 2,
    role: "You",
    partner: "Server",
    setting: "Dinner at a busy American restaurant.",
    turns: [
      { speaker: "partner", text: "Hi there! Can I start you off with something to drink?", model: "", concepts: [] },
      {
        speaker: "user",
        context: "Order a drink politely.",
        model: "Could I get an iced tea, please?",
        concepts: [["could i get", "can i get", "i'll have", "i'd like", "iced tea", "water", "please"]],
      },
      { speaker: "partner", text: "Of course. Are you ready to order, or do you need a minute?", model: "", concepts: [] },
      {
        speaker: "user",
        context: "Ask a quick question about the menu before deciding.",
        model: "What do you recommend? I can't decide between the burger and the fish.",
        concepts: [["recommend", "what do you recommend", "what's good", "can't decide", "suggest"]],
      },
      { speaker: "partner", text: "The burger is our most popular — it's really good.", model: "", concepts: [] },
      {
        speaker: "user",
        context: "Decide on the burger and order it.",
        model: "Great, I'll take the burger then. Could I get it with fries?",
        concepts: [["i'll take", "i'll have", "the burger", "burger", "fries"]],
        tip: "'I'll take…' / 'I'll have…' is the natural ordering pattern.",
      },
    ],
  },
];

/* ---------------- Achievements ---------------- */

export const ACHIEVEMENTS: AchievementDef[] = [
  { id: "first-session", title: "First Steps", desc: "Complete your first practice session.", icon: "flag" },
  { id: "mastered-10", title: "Getting There", desc: "Master 10 phrases.", icon: "sprout" },
  { id: "mastered-50", title: "Phrase Collector", desc: "Master 50 phrases.", icon: "books" },
  { id: "mastered-100", title: "Centurion", desc: "Master 100 phrases.", icon: "trophy" },
  { id: "streak-3", title: "Warming Up", desc: "Practice 3 days in a row.", icon: "flame" },
  { id: "streak-7", title: "One Week Strong", desc: "Practice 7 days in a row.", icon: "flame" },
  { id: "streak-30", title: "Unstoppable", desc: "Practice 30 days in a row.", icon: "zap" },
  { id: "medical-m1", title: "Clinical Voice", desc: "Pass your first Medical English module test.", icon: "cross" },
  { id: "accuracy-90", title: "Sharp Shooter", desc: "Finish a session with 90%+ accuracy (min. 10 exercises).", icon: "target" },
  { id: "xp-1000", title: "Momentum", desc: "Earn 1,000 total XP.", icon: "bolt" },
  { id: "longterm-1", title: "Built to Last", desc: "Move a phrase into long-term mastery.", icon: "anchor" },
  { id: "convo-3", title: "Conversation Starter", desc: "Complete 3 conversation scenarios.", icon: "chat" },
];

export const STATE_LABELS: Record<string, string> = {
  NEW: "New",
  LEARNING: "Learning",
  REVIEWING: "Reviewing",
  STRUGGLING: "Struggling",
  NEEDS_REVIEW: "Due for review",
  STRONG: "Strong",
  MASTERED: "Mastered",
  LONG_TERM_MASTERED: "Long-term",
};
